export const AUTH_USER = 'auth_user'
export const AUTH_USER_WITH_REDIRECT = 'auth_user_with_redirect'
export const AUTH_ERROR = 'auth_error'
export const AUTH_COMPLETED = 'auth_completed'
export const DID_GET_SCRIPT = 'did_get_script'
export const SCRIPT_ERROR = 'script_error'
export const UNAUTH_USER = 'unauth_user'
export const SET_EDITOR_STATE = 'set_editor_state'
