export const AUTH_USER = 'auth_user'
export const AUTH_ERROR = 'auth_error'
export const CHECK_AUTH = 'check_auth'
export const AUTH_COMPLETED = 'auth_completed'
export const DID_GET_SCRIPT = 'did_get_script'
export const SCRIPT_ERROR = 'script_error'
